/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    media: Media;
    properties: Property;
    bookings: Booking;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | HeroWithSearchBlock
    | TrustFeaturesBlock
    | FeaturedPropertiesBlock
    | AboutIntroBlock
    | StatsBarBlock
    | CoreValuesBlock
  )[];
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroWithSearchBlock".
 */
export interface HeroWithSearchBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  search: {
    action: string;
    locationLabel: string;
    locationPlaceholder: string;
    typeLabel: string;
    types: {
      label: string;
      value?: string | null;
      id?: string | null;
    }[];
    priceLabel: string;
    prices: {
      label: string;
      value?: string | null;
      id?: string | null;
    }[];
    buttonLabel: string;
  };
  backgroundImage: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero-with-search';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustFeaturesBlock".
 */
export interface TrustFeaturesBlock {
  items: {
    icon: 'home' | 'award' | 'handshake' | 'shield';
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'trust-features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPropertiesBlock".
 */
export interface FeaturedPropertiesBlock {
  eyebrow?: string | null;
  title: string;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Select from properties marked as featured for the home page.
   */
  properties: (number | Property)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featured-properties';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  name: string;
  status: 'for-sale' | 'for-rent';
  type: 'house' | 'apartment' | 'villa' | 'land' | 'commercial';
  featured?: boolean | null;
  price: number;
  location: string;
  summary?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  /**
   * Square feet
   */
  area?: number | null;
  parking?: number | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  listing?: {
    name?: string | null;
    verified?: boolean | null;
    image?: (number | null) | Media;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutIntroBlock".
 */
export interface AboutIntroBlock {
  eyebrow?: string | null;
  heading: string;
  body: {
    text: string;
    id?: string | null;
  }[];
  image: number | Media;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-intro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarBlock".
 */
export interface StatsBarBlock {
  items: {
    value: string;
    label: string;
    icon: 'key' | 'building' | 'clients' | 'award';
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats-bar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesBlock".
 */
export interface CoreValuesBlock {
  eyebrow?: string | null;
  heading: string;
  items: {
    icon: 'home' | 'excellence' | 'heart' | 'person' | 'shield' | 'handshake';
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'core-values';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  reference: string;
  submissionToken: string;
  fullName: string;
  email: string;
  phone: string;
  property: number | Property;
  interestType: 'buying' | 'renting' | 'selling' | 'investment';
  preferredDate: string;
  preferredTime:
    | '09:00'
    | '09:30'
    | '10:00'
    | '10:30'
    | '11:00'
    | '11:30'
    | '12:00'
    | '12:30'
    | '13:00'
    | '13:30'
    | '14:00'
    | '14:30'
    | '15:00'
    | '15:30'
    | '16:00'
    | '16:30'
    | '17:00';
  message?: string | null;
  status: 'new' | 'contacted' | 'confirmed' | 'completed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        'hero-with-search'?: T | HeroWithSearchBlockSelect<T>;
        'trust-features'?: T | TrustFeaturesBlockSelect<T>;
        'featured-properties'?: T | FeaturedPropertiesBlockSelect<T>;
        'about-intro'?: T | AboutIntroBlockSelect<T>;
        'stats-bar'?: T | StatsBarBlockSelect<T>;
        'core-values'?: T | CoreValuesBlockSelect<T>;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroWithSearchBlock_select".
 */
export interface HeroWithSearchBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  search?:
    | T
    | {
        action?: T;
        locationLabel?: T;
        locationPlaceholder?: T;
        typeLabel?: T;
        types?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        priceLabel?: T;
        prices?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        buttonLabel?: T;
      };
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustFeaturesBlock_select".
 */
export interface TrustFeaturesBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPropertiesBlock_select".
 */
export interface FeaturedPropertiesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  properties?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutIntroBlock_select".
 */
export interface AboutIntroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBarBlock_select".
 */
export interface StatsBarBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesBlock_select".
 */
export interface CoreValuesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  type?: T;
  featured?: T;
  price?: T;
  location?: T;
  summary?: T;
  description?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  bedrooms?: T;
  bathrooms?: T;
  area?: T;
  parking?: T;
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  listing?:
    | T
    | {
        name?: T;
        verified?: T;
        image?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  reference?: T;
  submissionToken?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  property?: T;
  interestType?: T;
  preferredDate?: T;
  preferredTime?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}